version: '3.2'

services:
  web:
    image: php:7-apache
    container_name: course.web
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - ./../:/var/www/course
    depends_on:
      - course.db
  db:
    image: postgres:14.1
    container_name: course.db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: course
      POSTGRES_DB: course
      POSTGRES_PASSWORD: "${POSTGRES_ROOT_PASSWORD}"
    volumes:
      - /postgres/init:/docker-entrypoint-initdb.d
      - ./var/lib/postgresql/data/:/var/lib/postgresql/data