version: '3.2'

services:
  course.web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - ./../:/var/www/course
    depends_on:
      - course.db
    networks:
      default:
        aliases:
          - "course.web.host"

  course.db:
    image: postgres:14.1
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: course
      POSTGRES_DB: course
      POSTGRES_PASSWORD: "${POSTGRES_ROOT_PASSWORD}"
    volumes:
      - /db/:/docker-entrypoint-initdb.d
      - /db/var/lib/postgresql/data/:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - "course.db.host"